2023-03-11 19:26:03,115 [INFO   ] [APP] exchange started with arguments={rtg.py, run, autotrader.py}
2023-03-11 19:26:03,115 [INFO   ] [APP] configuration={"Engine":{"MarketDataFile":"data/market_data1.csv","MarketEventInterval":0.05,"MarketOpenDelay":5.0,"MatchEventsFile":"match_events.csv","ScoreBoardFile":"score_board.csv","Speed":10.0,"TickInterval":0.25},"Execution":{"Host":"127.0.0.1","Port":12345},"Fees":{"Maker":-0.0001,"Taker":0.0002},"Hud":{"Host":"127.0.0.1","Port":12347},"Information":{"Type":"mmap","Name":"info.dat"},"Instrument":{"EtfClamp":0.002,"TickSize":1.0},"Limits":{"ActiveOrderCountLimit":10,"ActiveVolumeLimit":200,"MessageFrequencyInterval":1.0,"MessageFrequencyLimit":50,"PositionLimit":100},"Traders":{"TraderOne":"secret","TraderTwo":"secret"}}
2023-03-11 19:26:03,116 [INFO   ] [CONTROLLER] starting the match
2023-03-11 19:26:03,116 [INFO   ] [EXECUTION] starting execution server: host=127.0.0.1 port=12345
2023-03-11 19:26:03,116 [INFO   ] [INFORMATION] starting information publisher: type=mmap name=info.dat
2023-03-11 19:26:03,120 [INFO   ] [HEADS_UP] starting heads-up display server: host=127.0.0.1 port=12347
2023-03-11 19:26:03,120 [INFO   ] [INFORMATION] information channel established
2023-03-11 19:26:03,303 [INFO   ] [CONNECTION] fd=24 connection established: peer=127.0.0.1:64109
2023-03-11 19:26:03,304 [INFO   ] [EXECUTION] fd=24 'TraderOne' is ready!
2023-03-11 19:26:04,500 [INFO   ] [CONNECTION] fd=25 connection established: peer=127.0.0.1:64111
2023-03-11 19:26:08,125 [INFO   ] [CONTROLLER] market open
2023-03-11 19:26:08,209 [ERROR  ] [CONNECTION] fd=24 connection lost:
Traceback (most recent call last):
  File "/Users/huba/.pyenv/versions/3.9.16/lib/python3.9/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer
2023-03-11 19:26:08,209 [WARNING] [EXECUTION] fd=24 lost connection to auto-trader:
Traceback (most recent call last):
  File "/Users/huba/.pyenv/versions/3.9.16/lib/python3.9/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer
2023-03-11 19:26:10,298 [INFO   ] [APP] SIGTERM signal received - shutting down...
2023-03-11 19:26:10,298 [INFO   ] [APP] closing event loop
2023-03-11 19:29:05,638 [INFO   ] [APP] exchange started with arguments={rtg.py, run, autotrader.py}
2023-03-11 19:29:05,638 [INFO   ] [APP] configuration={"Engine":{"MarketDataFile":"data/market_data1.csv","MarketEventInterval":0.05,"MarketOpenDelay":5.0,"MatchEventsFile":"match_events.csv","ScoreBoardFile":"score_board.csv","Speed":10.0,"TickInterval":0.25},"Execution":{"Host":"127.0.0.1","Port":12345},"Fees":{"Maker":-0.0001,"Taker":0.0002},"Hud":{"Host":"127.0.0.1","Port":12347},"Information":{"Type":"mmap","Name":"info.dat"},"Instrument":{"EtfClamp":0.002,"TickSize":1.0},"Limits":{"ActiveOrderCountLimit":10,"ActiveVolumeLimit":200,"MessageFrequencyInterval":1.0,"MessageFrequencyLimit":50,"PositionLimit":100},"Traders":{"TraderOne":"secret","TraderTwo":"secret"}}
2023-03-11 19:29:05,638 [INFO   ] [CONTROLLER] starting the match
2023-03-11 19:29:05,638 [INFO   ] [EXECUTION] starting execution server: host=127.0.0.1 port=12345
2023-03-11 19:29:05,638 [INFO   ] [INFORMATION] starting information publisher: type=mmap name=info.dat
2023-03-11 19:29:05,643 [INFO   ] [HEADS_UP] starting heads-up display server: host=127.0.0.1 port=12347
2023-03-11 19:29:05,643 [INFO   ] [INFORMATION] information channel established
2023-03-11 19:29:05,801 [INFO   ] [CONNECTION] fd=24 connection established: peer=127.0.0.1:64167
2023-03-11 19:29:05,801 [INFO   ] [EXECUTION] fd=24 'TraderOne' is ready!
2023-03-11 19:29:06,991 [INFO   ] [CONNECTION] fd=25 connection established: peer=127.0.0.1:64169
2023-03-11 19:29:10,647 [INFO   ] [CONTROLLER] market open
2023-03-11 19:29:10,727 [ERROR  ] [CONNECTION] fd=24 connection lost:
Traceback (most recent call last):
  File "/Users/huba/.pyenv/versions/3.9.16/lib/python3.9/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer
2023-03-11 19:29:10,728 [WARNING] [EXECUTION] fd=24 lost connection to auto-trader:
Traceback (most recent call last):
  File "/Users/huba/.pyenv/versions/3.9.16/lib/python3.9/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer
2023-03-11 19:29:12,376 [INFO   ] [APP] SIGTERM signal received - shutting down...
2023-03-11 19:29:12,376 [INFO   ] [APP] closing event loop
2023-03-11 19:30:32,836 [INFO   ] [APP] exchange started with arguments={rtg.py, run, autotrader.py}
2023-03-11 19:30:32,836 [INFO   ] [APP] configuration={"Engine":{"MarketDataFile":"data/market_data1.csv","MarketEventInterval":0.05,"MarketOpenDelay":5.0,"MatchEventsFile":"match_events.csv","ScoreBoardFile":"score_board.csv","Speed":10.0,"TickInterval":0.25},"Execution":{"Host":"127.0.0.1","Port":12345},"Fees":{"Maker":-0.0001,"Taker":0.0002},"Hud":{"Host":"127.0.0.1","Port":12347},"Information":{"Type":"mmap","Name":"info.dat"},"Instrument":{"EtfClamp":0.002,"TickSize":1.0},"Limits":{"ActiveOrderCountLimit":10,"ActiveVolumeLimit":200,"MessageFrequencyInterval":1.0,"MessageFrequencyLimit":50,"PositionLimit":100},"Traders":{"TraderOne":"secret","TraderTwo":"secret"}}
2023-03-11 19:30:32,836 [INFO   ] [CONTROLLER] starting the match
2023-03-11 19:30:32,836 [INFO   ] [EXECUTION] starting execution server: host=127.0.0.1 port=12345
2023-03-11 19:30:32,836 [INFO   ] [INFORMATION] starting information publisher: type=mmap name=info.dat
2023-03-11 19:30:32,841 [INFO   ] [HEADS_UP] starting heads-up display server: host=127.0.0.1 port=12347
2023-03-11 19:30:32,841 [INFO   ] [INFORMATION] information channel established
2023-03-11 19:30:33,030 [INFO   ] [CONNECTION] fd=24 connection established: peer=127.0.0.1:64195
2023-03-11 19:30:33,030 [INFO   ] [EXECUTION] fd=24 'TraderOne' is ready!
2023-03-11 19:30:34,215 [INFO   ] [CONNECTION] fd=25 connection established: peer=127.0.0.1:64196
2023-03-11 19:30:37,844 [INFO   ] [CONTROLLER] market open
2023-03-11 19:30:37,926 [ERROR  ] [CONNECTION] fd=24 connection lost:
Traceback (most recent call last):
  File "/Users/huba/.pyenv/versions/3.9.16/lib/python3.9/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer
2023-03-11 19:30:37,927 [WARNING] [EXECUTION] fd=24 lost connection to auto-trader:
Traceback (most recent call last):
  File "/Users/huba/.pyenv/versions/3.9.16/lib/python3.9/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer
2023-03-11 19:30:39,773 [INFO   ] [APP] SIGTERM signal received - shutting down...
2023-03-11 19:30:39,773 [INFO   ] [APP] closing event loop
